package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/kuchkin/mumax3-gneb/cuda/cu"
	"github.com/kuchkin/mumax3-gneb/timer"
	"sync"
	"unsafe"
)

// CUDA handle for copyBeff kernel
var copyBeff_code cu.Function

// Stores the arguments for copyBeff kernel invocation
type copyBeff_args_t struct {
	arg_Bx2   unsafe.Pointer
	arg_By2   unsafe.Pointer
	arg_Bz2   unsafe.Pointer
	arg_Bx    unsafe.Pointer
	arg_By    unsafe.Pointer
	arg_Bz    unsafe.Pointer
	arg_noi   int
	arg_image int
	arg_Nx    int
	arg_Ny    int
	arg_Nz    int
	argptr    [11]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for copyBeff kernel invocation
var copyBeff_args copyBeff_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	copyBeff_args.argptr[0] = unsafe.Pointer(&copyBeff_args.arg_Bx2)
	copyBeff_args.argptr[1] = unsafe.Pointer(&copyBeff_args.arg_By2)
	copyBeff_args.argptr[2] = unsafe.Pointer(&copyBeff_args.arg_Bz2)
	copyBeff_args.argptr[3] = unsafe.Pointer(&copyBeff_args.arg_Bx)
	copyBeff_args.argptr[4] = unsafe.Pointer(&copyBeff_args.arg_By)
	copyBeff_args.argptr[5] = unsafe.Pointer(&copyBeff_args.arg_Bz)
	copyBeff_args.argptr[6] = unsafe.Pointer(&copyBeff_args.arg_noi)
	copyBeff_args.argptr[7] = unsafe.Pointer(&copyBeff_args.arg_image)
	copyBeff_args.argptr[8] = unsafe.Pointer(&copyBeff_args.arg_Nx)
	copyBeff_args.argptr[9] = unsafe.Pointer(&copyBeff_args.arg_Ny)
	copyBeff_args.argptr[10] = unsafe.Pointer(&copyBeff_args.arg_Nz)
}

// Wrapper for copyBeff CUDA kernel, asynchronous.
func k_copyBeff_async(Bx2 unsafe.Pointer, By2 unsafe.Pointer, Bz2 unsafe.Pointer, Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, noi int, image int, Nx int, Ny int, Nz int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("copyBeff")
	}

	copyBeff_args.Lock()
	defer copyBeff_args.Unlock()

	if copyBeff_code == 0 {
		copyBeff_code = fatbinLoad(copyBeff_map, "copyBeff")
	}

	copyBeff_args.arg_Bx2 = Bx2
	copyBeff_args.arg_By2 = By2
	copyBeff_args.arg_Bz2 = Bz2
	copyBeff_args.arg_Bx = Bx
	copyBeff_args.arg_By = By
	copyBeff_args.arg_Bz = Bz
	copyBeff_args.arg_noi = noi
	copyBeff_args.arg_image = image
	copyBeff_args.arg_Nx = Nx
	copyBeff_args.arg_Ny = Ny
	copyBeff_args.arg_Nz = Nz

	args := copyBeff_args.argptr[:]
	cu.LaunchKernel(copyBeff_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("copyBeff")
	}
}

// maps compute capability on PTX code for copyBeff kernel.
var copyBeff_map = map[int]string{0: "",
	50: copyBeff_ptx_50}

// copyBeff PTX code for various compute capabilities.
const (
	copyBeff_ptx_50 = `
.version 7.5
.target sm_50
.address_size 64

	// .globl	copyBeff

.visible .entry copyBeff(
	.param .u64 copyBeff_param_0,
	.param .u64 copyBeff_param_1,
	.param .u64 copyBeff_param_2,
	.param .u64 copyBeff_param_3,
	.param .u64 copyBeff_param_4,
	.param .u64 copyBeff_param_5,
	.param .u32 copyBeff_param_6,
	.param .u32 copyBeff_param_7,
	.param .u32 copyBeff_param_8,
	.param .u32 copyBeff_param_9,
	.param .u32 copyBeff_param_10
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [copyBeff_param_0];
	ld.param.u64 	%rd2, [copyBeff_param_1];
	ld.param.u64 	%rd3, [copyBeff_param_2];
	ld.param.u64 	%rd4, [copyBeff_param_3];
	ld.param.u64 	%rd5, [copyBeff_param_4];
	ld.param.u64 	%rd6, [copyBeff_param_5];
	ld.param.u32 	%r4, [copyBeff_param_7];
	ld.param.u32 	%r5, [copyBeff_param_8];
	ld.param.u32 	%r6, [copyBeff_param_9];
	ld.param.u32 	%r7, [copyBeff_param_10];
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd7, %rd1;
	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r18, %r17, %r5, %r1;
	mad.lo.s32 	%r19, %r7, %r4, %r3;
	mad.lo.s32 	%r20, %r19, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	cvta.to.global.u64 	%rd10, %rd4;
	mul.wide.s32 	%rd11, %r21, 4;
	add.s64 	%rd12, %rd10, %rd11;
	st.global.f32 	[%rd12], %f1;
	cvta.to.global.u64 	%rd13, %rd2;
	add.s64 	%rd14, %rd13, %rd8;
	ld.global.nc.f32 	%f2, [%rd14];
	cvta.to.global.u64 	%rd15, %rd5;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f2;
	cvta.to.global.u64 	%rd17, %rd3;
	add.s64 	%rd18, %rd17, %rd8;
	ld.global.nc.f32 	%f3, [%rd18];
	cvta.to.global.u64 	%rd19, %rd6;
	add.s64 	%rd20, %rd19, %rd11;
	st.global.f32 	[%rd20], %f3;

$L__BB0_2:
	ret;

}

`
)
